# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
before_install:
  #- sudo apt-get -qq update
  #- sudo apt-get install -y radiance
  - scripts/install-radiance.sh
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test ARGS="-V"
